name: Portfolio
favicon: null
layout_spectrum: 0.75602
typography_spectrum: 0.25602
title: Portfolio Urs Breton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-46750938-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#95b3ef'
    - '#fe364a'
    - '#01e3fb'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
