name: Portfolio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83166
title: Portfolio Urs Breton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-46750938-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffde5'
    - '#0b1618'
    - '#dcc7b1'
    - '#832d31'
    - '#ae754d'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
