name: Site
favicon: null
layout_spectrum: 0.99122
typography_spectrum: 0.50098
title: The Grid messes up my portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-46750938-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7d8a2e'
    - '#c9d787'
    - '#ff8598'
    - '#ffffff'
    - '#0c0d08'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
