name: Portfolio
favicon: null
layout_spectrum: 0.75602
typography_spectrum: 0.25602
title: The Grid messes up my portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-46750938-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a7312f'
    - '#151716'
    - '#2f9971'
    - '#ec6e58'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
