name: Portfolio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04228788870386779
title: Portfolio Urs Breton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-46750938-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
